import { Button, ComboBox, HorizontalBox, LineEdit, Palette, StyleMetrics, TextEdit, VerticalBox, Switch } from "std-widgets.slint";
import { SideSection } from "../widgets/side_section.slint";
import { SideRow } from "../widgets/side_row.slint";
import { SplitLine } from "../widgets/split_line.slint";

export global Options {
    in property <bool> key-ready: false;
    private property <bool> ready;
    in property <[string]> sps;
    out property <string> dp-text;
    in-out property <bool> name;
    callback append-dp-text(string);
    callback lsn();
    callback obsr();
    callback parse(bool);
    callback key-send(string);
    callback send-test(string);
    callback send-sm3(string);
    callback send-sm4e-cbc(string, string);
    callback send-sm4e-ecb(string);
    callback chat-send-sm4e-ecb(string);
    callback send-sm4d-cbc(string, string);
    callback send-sm4d-ecb(string);
    callback sp-open(int) -> bool;
    append-dp-text(newline) => {
        dp-text += newline + "\n";
    }
}

export component HomePage inherits HorizontalLayout {
    Rectangle {
        background: Palette.background.darker(0.3);
        VerticalLayout {
            alignment: start;
            padding-left: StyleMetrics.layout-padding;
            padding-right: StyleMetrics.layout-padding;
            SideSection {
                title: "设备";
                SideRow {
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: "串口";
                    }

                    sp-box := ComboBox {
                        model: Options.sps;
                        selected => {
                            open-button.checked = false;
                        }
                    }
                }

                SideRow {
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: "状态";
                    }

                    open-button := Button {
                        enabled: 0 != Options.sps.length;
                        text: self.checked ? "已连接" : "打开";
                        width: 200px;
                        clicked => {
                            self.checked = Options.sp-open(sp-box.current-index);
                        }
                    }
                }
            }

            SplitLine { }

            SideSection {
                title: "操作";
                SideRow {
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: "类型";
                    }

                    op-box := ComboBox {
                        model: [
                            "串口回显",
                            "SM3 散列",
                            "SM4 加密",
                            "SM4 解密",
                            "加密通信",
                            "观测"
                        ];
                        enabled: open-button.checked;
                        selected(tp) => {
                            if (self.model[0] == tp) {
                                Options.lsn();
                            } else if (self.model[4] == tp) {
                                Options.parse(true);
                            } else if (self.model[5] == tp) {
                                Options.obsr();
                            } else {
                                Options.parse(false);
                            }
                        }
                    }
                }
            }

            SplitLine { }

            SideSection {
                visible: 2 == op-box.current-index || 3 == op-box.current-index || 4 == op-box.current-index;
                title: "SM4";
                SideRow {
                    visible: parent.enabled;
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: "密钥";
                    }

                    key-line := LineEdit {
                        enabled: op-box.current-index != 0;
                        placeholder-text: "(HEX)";
                        edited => {
                            Options.key-ready = false;
                        }
                    }
                }

                SideRow {
                    visible: parent.enabled;
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: "模式";
                    }

                    mode-box := ComboBox {
                        enabled: op-box.current-index != 0 && Options.key-ready;
                        model: ["ECB", "CBC"];
                    }
                }

                SideRow {
                    visible: parent.enabled;
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: "IV";
                    }

                    iv-line := LineEdit {
                        enabled: 0 == mode-box.current-index && Options.key-ready;
                        placeholder-text: "(HEX)";
                    }
                }

                key-button := Button {
                    visible: parent.enabled;
                    primary: Options.key-ready;
                    text: self.primary ? "密钥发送成功" : "注入密钥";
                    clicked => {
                        Options.key-send(key-line.text);
                    }
                }
            }
        }
    }

    VerticalBox {
        dp-edit := TextEdit {
            read-only: true;
            text: Options.dp-text;
        }

        HorizontalBox {
            padding: 0;
            VerticalBox {
                padding: 0;
                HorizontalLayout {
                    spacing: StyleMetrics.layout-spacing;
                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: op-box.current-index == 3 ? "密文（HEX）" : "消息（UTF-8）";
                    }

                    pc-line := LineEdit {
                        height: 40px;
                    }

                    Text {
                        vertical-alignment: center;
                        horizontal-alignment: left;
                        font-size: 1.25rem;
                        text: ab.checked == true ? "Bob" : "Alice";
                    }

                    ab := Switch {
                        enabled: op-box.current-index == 4 && Options.key-ready;
                        checked <=> Options.name;
                    }
                }
            }

            send-button := Button {
                enabled: open-button.checked && (0 == op-box.current-index || 1 == op-box.current-index || key-button.primary);
                primary: true;
                text: "发送";
                width: 160px;
                height: 40px;
                clicked => {
                    if (0 == op-box.current-index) {
                        Options.send-test(pc-line.text);
                    } else if (1 == op-box.current-index) {
                        Options.send-sm3(pc-line.text);
                    } else if (op-box.current-index == 2 && mode-box.current-index == 0) {
                        Options.send-sm4e-ecb(pc-line.text);
                    } else if (op-box.current-index == 2 && mode-box.current-index == 1) {
                        Options.send-sm4e-cbc(pc-line.text, iv-line.text);
                    } else if (op-box.current-index == 3 && mode-box.current-index == 0) {
                        Options.send-sm4d-ecb(pc-line.text);
                    } else if (op-box.current-index == 3 && mode-box.current-index == 1) {
                        Options.send-sm4d-cbc(pc-line.text, iv-line.text);
                    } else {
                        Options.chat-send-sm4e-ecb(pc-line.text);
                    }
                }
            }
        }
    }
}
