import { AboutPage } from "./pages/about.slint";
import { HomePage, Options } from "./pages/home.slint";
import { TabWidget } from "std-widgets.slint";

export { Options }
export component AppWindow inherits Window {
    // in property <[string]> sps <=> sp-box.model;
    // private property <bool> send-ready <=> send-button.checkable;
    // private property <bool> sp-ready <=> open-button.checked;
    // private property <bool> key-ready <=> key-button.checked;
    // private property <int> sp-idx <=> sp-box.current-index;
    // private property <int> mode <=> cipher.current-index;
    // private property <string> result-text <=> text.text;
    // private property <int> key-len: 0;
    // callback key-send(string) -> bool;
    // callback send-sm3(string) -> string;
    // callback send-sm4e(string) -> string;
    // callback send-sm4d(string) -> string;
    // callback sp-open(int) -> bool;
    icon: @image-url("./resources/icons/icon.png");
    title: "待定";
    min-width: 800px;
    min-height: 450px;

    TabWidget {
        Tab {
            title: "主页";
            HomePage {}
        }

        Tab {
            title: "关于";
            AboutPage {
                width: 40%;
            }
        }
    }
}
