import { AboutPage } from "./pages/about.slint";
import { HomePage, Options } from "./pages/home.slint";
import { TabWidget } from "std-widgets.slint";

export { Options }
export component AppWindow inherits Window {
    icon: @image-url("./resources/icons/icon.png");
    title: "国密";
    min-width: 800px;
    min-height: 450px;

    TabWidget {
        Tab {
            title: "主页";
            HomePage {}
        }

        Tab {
            title: "关于";
            AboutPage {
                width: 40%;
            }
        }
    }
}
